[package]
authors = ["Cristian Cobzarenco <cristi.cobzarenco@gmail.com>"]
name = "rs_doom"
version = "0.0.8"

[[bin]]
name = "rs_doom"

[dependencies]
wad = { path = "wad" }
engine = { path = "engine" }
game = { path = "game" }
math = { path = "math" }

clap = "2.26.0"
env_logger = "0.4.3"
error-chain = "0.11.0"
log = "0.3.6"
time = "0.1.35"

[dependencies.sdl2]
features = ["ttf"]
version = "0.30.0"

[workspace]
